### ISSUE TITLE
issue adding staff 

### ISSUE THREAD

**Issue by KillerWerot** [Brynlai/RestaurantProject#301]
i logged in with staff #7 and tried to add staff and this is what it shows

: Uncaught TypeError: mysqli_query(): Argument #1 ($mysql) must be of type mysqli, null given in C:\xampp\htdocs\adminSide\staffCrud\createStaff.php:43 Stack trace: #0 C:\xampp\htdocs\adminSide\staffCrud\createStaff.php(43): mysqli_query(NULL, 'SELECT MAX(staf...') #1 C:\xampp\htdocs\adminSide\staffCrud\createStaff.php(50): getNextAvailableStaffID(NULL) #2 {main} thrown in

**Comment by BryanTheLai** [comment]
Fix it should be fine now

https://github.com/BryanTheLai/RestaurantProject/commit/4ebe3cfdee13305d9e14cdb9e1a5424098984e34
